controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Good;
use app\models\Order;
use app\models\OrderPhoto;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\HttpException;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Index
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Choose a photo
     *
     */
    public function actionChoose($user_id = null, $max_id = null, $season = null)
    {
        if (Yii::$app->user->isGuest) {
            $this->redirect(['site/index']);
        } else {
            if ($user_id == null) {
                $user_id = Yii::$app->user->identity->instagram_id;
            }

            if ($season == null) {
                $data = Yii::$app->instagram->userMediaRecent($user_id, 20, $max_id);
            } else {
                $months = [];
                switch ($season) {
                    case 'fall':
                        $months = [9, 10, 11];
                        break;
                    case 'winter':
                        $months = [12, 1, 2];
                        break;

                    case 'spring':
                        $months = [3, 4, 5];
                        break;
                    case 'summer':
                        $months = [6, 7, 8];
                        break;
                }
                $data = Yii::$app->instagram->userMediaForMonths($user_id, $months);
            }

            if (isset($data['pagination']) && isset($data['pagination']['next_max_id'])) {
                $max_id = $data['pagination']['next_max_id'];
            } else {
                $max_id = null;
            }

            if (Yii::$app->request->isAjax) {
                return $this->renderPartial('_photos', ['photos' => $data['data'], 'max_id' => $max_id, 'user_id' => $user_id]);
            } else {
                return $this->render('choose', ['data' => $data, 'user_id' => $user_id, 'max_id' => $max_id]);
            }
        }
    }

    /**
     * Choose a wear
     *
     * @param null $id
     * @return string
     * @throws \yii\web\HttpException
     */
    public function actionWear($id = null)
    {
        if ($id == null) {
            $order = new Order();
            $order->user_id = Yii::$app->user->identity->id;

            if ($order->save()) {
                if (isset($_POST['photo'])) {
                    foreach ($_POST['photo'] as $instagram_id) {
                        $orderPhoto = new OrderPhoto();
                        $orderPhoto->instagram_id = $instagram_id;
                        $orderPhoto->order_id = $order->id;
                        if (!$orderPhoto->save()) {
                            throw new HttpException(500);
                        }
                    }
                    $this->redirect(['wear', 'id' => $order->id]);
                } else {
                    throw new HttpException(400);
                }
            } else {
                throw new HttpException(500);
            }
        } else {
            $order = Order::find()->where(['id' => $id])->one();
            if ($order != null) {
                if (Yii::$app->request->isPost) {
                    if ($order->load(Yii::$app->request->post())) {
                        $good = Good::find()->where(['type' => $_POST['Good']['type'], 'wear' => $_POST['Good']['wear']])->one();
                        if ($good != null) {
                            $order->good_id = $good->id;
                            if ($order->save()) {
                                $this->redirect(['site/form', 'id' => $order->id]);
                            }
                        } else {
                            throw new HttpException(500, 'Нельзя оформить заказ на несуществующий товар');
                        }
                    }
                }
            } else {
                throw new HttpException(404);
            }
        }
        return $this->render('wear', ['order' => $order]);
    }

    public function actionWearsizes($type, $wear)
    {
        $wear = Good::find()->where(['type' => $type, 'wear' => $wear])->one();
        return $this->renderPartial('wearsizes', ['good' => $wear]);
    }

    public function actionWearphotos($type, $wear)
    {
        $wear = Good::find()->where(['type' => $type, 'wear' => $wear])->one();
        return $this->renderPartial('wearphotos', ['good' => $wear]);
    }

    public function actionWearprices($type, $wear)
    {
        $wear = Good::find()->where(['type' => $type, 'wear' => $wear])->one();
        return $this->renderPartial('wearprices', ['good' => $wear]);
    }

    public function actionForm($id)
    {
        $order = Order::find()->where(['id' => $id])->one();

        if (($order->load(Yii::$app->request->post())) && ($order->save())) {
            $this->redirect(['site/thankyou']);
        }

        if ($order != null) {
            return $this->render('form', ['order' => $order]);
        } else {
            throw new HttpException(404);
        }
    }

    public function actionThankyou()
    {
        return $this->render('thankyou');
    }

    public function actionUpload($id = null, $delete_photo = null)
    {
        if ($delete_photo != null) {
            $photo = OrderPhoto::find()->where(['id' => $delete_photo])->one();
            if ($photo != null) {
                $photo->delete();
            }
            if (Yii::$app->request->isAjax) {
                return Json::encode(['status' => 'success']);
            } else {
                $this->redirect(['upload', 'id' => $id]);
            }
        }
        if ($id != null) {
            $order = Order::find()->where(['id' => $id])->one();
            if ($order == null) {
                throw new HttpException(404);
            }
        } else {
            $order = new Order();
        }

        if (Yii::$app->request->isPost) {
            $order->load(Yii::$app->request->post());
            if ($order->save()) {
                foreach ($_FILES['files']['error'] as $index => $value) {
                    if ($value == 0) {
                        $parts = explode('.', $_FILES['files']['name'][$index]);

                        $file_name = 'upload/n_' . time() . '_' . mt_rand(100000, 999999) . '.' . array_pop($parts);

                        if (move_uploaded_file($_FILES['files']['tmp_name'][$index], $file_name)) {
                            $orderPhoto = new OrderPhoto();
                            $orderPhoto->order_id = $order->id;
                            $orderPhoto->url = $file_name;
                            $orderPhoto->save();
                        }

                        if ($order->photoCount >= 20) {
                            break;
                        }
                    }
                }

                if (isset($_POST['OrderPhoto'])) {
                    foreach ($_POST['OrderPhoto'] as $id) {
                        $photo = OrderPhoto::find()->where(['id' => $id])->one();
                        $photo->order_id = $order->id;
                        $photo->save();
                    }
                }

                $this->redirect(['upload', 'id' => $order->id]);
            } else {
                throw new HttpException(500);
            }
        }
        return $this->render('upload', ['order' => $order]);
    }

    /**
     * @return string
     */
    public function actionUploadimage()
    {
        if ($_FILES['image']['error'] == 0) {
            $parts = explode('.', $_FILES['image']['name']);

            $file_name = 'upload/n_' . time() . '_' . mt_rand(100000, 999999) . '.' . array_pop($parts);

            if (move_uploaded_file($_FILES['image']['tmp_name'], $file_name)) {
                $orderPhoto = new OrderPhoto();
                $orderPhoto->url = $file_name;
                if ($orderPhoto->save()) {
                    $data['id'] = $orderPhoto->id;
                    $data['url'] = Yii::getAlias('@web') . '/' . $file_name;
                    return Json::encode($data);
                }
            }
        }
    }

    /**
     * Logout
     *
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

views/layouts/main.php
<?php
use app\models\Callback;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Button;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use app\assets\AppAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
    <!DOCTYPE html>

    <html lang="<?= Yii::$app->language ?>">
    <head>
        <!-- Meta -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <?= Html::csrfMetaTags() ?>

        <title><?= Html::encode($this->title) ?></title>

        <?php $this->head() ?>
        <!-- Bootstrap Core CSS -->
        <link href="<?= Yii::getAlias('@web') ?>/css/bootstrap.min.css" rel="stylesheet">

        <!-- Customizable CSS -->
        <link href="<?= Yii::getAlias('@web') ?>/css/main.css" rel="stylesheet" data-skrollr-stylesheet>
        <link href="<?= Yii::getAlias('@web') ?>/css/green.css" rel="stylesheet" title="Color">
        <link href="<?= Yii::getAlias('@web') ?>/css/owl.carousel.css" rel="stylesheet">
        <link href="<?= Yii::getAlias('@web') ?>/css/owl.transitions.css" rel="stylesheet">
        <link href="<?= Yii::getAlias('@web') ?>/css/animate.min.css" rel="stylesheet">
        <link href="<?= Yii::getAlias('@web') ?>/css/font-awesome.min.css" rel="stylesheet">

        <!-- Fonts -->
        <link href="//fonts.googleapis.com/css?family=Lato:400,900,300,700" rel="stylesheet">
        <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic"
              rel="stylesheet">

        <!-- Icons/Glyphs -->
        <link href="<?= Yii::getAlias('@web') ?>/fonts/fontello.css" rel="stylesheet">

        <!-- Favicon -->
        <link rel="shortcut icon" href="<?= Yii::getAlias('@web') ?>/images/favicon.ico">

        <script src="<?= Yii::getAlias('@web') ?>/js/jquery.min.js"></script>

        <!-- HTML5 elements and media queries Support for IE8 : HTML5 shim and Respond.js -->
        <!--[if lt IE 9]>
        <script src="<?= Yii::getAlias('@web') ?>/js/html5shiv.js"></script>
        <script src="<?= Yii::getAlias('@web') ?>/js/respond.min.js"></script>
        <![endif]-->

        <style>
            .btn-red {
                background-color: #fd6b62;
            }
        </style>
    </head>

    <body>

    <?php
    $callbackWidget = Modal::begin([
        'header' => 'Закажите обратный звонок',
        'options' => ['style' => 'z-index: 10000']
    ]);

    $newCallback = new Callback();

    $form = ActiveForm::begin(['action' => ['callback/create']]);
    echo $form->field($newCallback, 'name')->textInput();
    echo $form->field($newCallback, 'phone')->textInput();

    echo Button::widget([
        'label' => 'Отправить',
        'options' => ['type' => 'submit']
    ]);

    ActiveForm::end();

    Modal::end();
    ?>

    <header>
        <div class="navbar">

            <div class="navbar-header">
                <div class="container">

                    <ul class="info pull-left">
                        <li><a href="<?= Yii::getAlias('@web') ?>">Уникальная одежда из фотографий с Instagram</a></li>
                    </ul>

                    <ul class="info pull-right">
                        <li><?= Html::a('У меня нет Instagram ;(', ['site/upload']); ?></li>
                    </ul>

                    <a class="navbar-brand" href="/"><img src="<?= Yii::getAlias('@web') ?>/images/logo.svg"></a>

                    <a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i
                            class='icon-menu-1'></i></a>

                </div>
            </div>

            <style>
                li.active {
                    font-weight: bold;
                }
            </style>
            <div class="yamm">
                <div class="navbar-collapse collapse">
                    <div class="container">
                        <a class="navbar-brand" href="<?= Yii::getAlias('@web') ?>"><img
                                src="<?= Yii::getAlias('@web') ?>/images/logo.svg"
                                class="logo"
                                alt=""></a>
                        <ul class="nav navbar-nav">
                            <li class="<?= $this->context->action->id == 'index' ? 'active' : '' ?>">
                                <span>1. Вход в Instagram</span>
                            </li>

                            <li class="<?= $this->context->action->id == 'choose' ? 'active' : '' ?>">
                                <span>2. Выбор фото</span>
                            </li>

                            <li class="<?= $this->context->action->id == 'wear' ? 'active' : '' ?>">
                                <span>3. Выбор одежды</span>
                            </li>

                            <li class="<?= $this->context->action->id == 'form' ? 'active' : '' ?>">
                                <span>4. Выши данные</span>
                            </li>

                            <li>
                                <span>= 2,5 минуты</span>
                            </li>

                        </ul>

                        <ul class="nav navbar-nav pull-right" style="padding: 0;">
                            <li style="text-align: center;">
                                <span style="font-size: 15px; font-weight: bold; padding: 0; margin: 0;">
                                    <span class="tel" style="font-size: 25px">8 800 700 34 52</span><br>
                                    <?= Html::a('заказать обратный звонок', '#', ['data-target' => '#' . $callbackWidget->id, 'data-toggle' => 'modal', 'style' => 'border-bottom: 1px dashed']); ?></span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <?= $content ?>

    <footer class="dark-bg">

        <div class="footer-bottom">
            <div class="container inner">
                <p class="pull-left"></p>
                <ul class="footer-menu pull-right">

                </ul>
            </div>
        </div>
    </footer>

    <script src="<?= Yii::getAlias('@web') ?>/js/jquery.min.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/jquery.easing.1.3.min.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/jquery.form.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/jquery.validate.min.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/bootstrap.min.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/bootstrap-hover-dropdown.min.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/skrollr.min.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/skrollr.stylesheets.min.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/waypoints.min.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/waypoints-sticky.min.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/owl.carousel.min.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/jquery.isotope.min.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/jquery.easytabs.min.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/google.maps.api.v3.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/viewport-units-buggyfill.js"></script>
    <script src="<?= Yii::getAlias('@web') ?>/js/scripts.js"></script>

    <script src="<?= Yii::getAlias('@web') ?>/switchstylesheet/switchstylesheet.js"></script>

    <script>
        $(document).ready(function () {
            $(".changecolor").switchstylesheet({ seperator: "color"});
        });
    </script>
    <!-- For demo purposes – can be removed on production : End -->
    </body>
    </html>
<?php $this->endPage() ?>