controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Good;
use app\models\Order;
use app\models\OrderPhoto;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\web\HttpException;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Index
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Choose a photo
     *
     */
    public function actionChoose($user_id = null, $max_id = null, $season = null)
    {
        if (Yii::$app->user->isGuest) {
            $this->redirect(['site/index']);
        } else {
            if ($user_id == null) {
                $user_id = Yii::$app->user->identity->instagram_id;
            }

            if ($season == null) {
                $data = Yii::$app->instagram->userMediaRecent($user_id, 20, $max_id);
            } else {
                $months = [];
                switch ($season) {
                    case 'fall':
                        $months = [9, 10, 11];
                        break;
                    case 'winter':
                        $months = [12, 1, 2];
                        break;

                    case 'spring':
                        $months = [3, 4, 5];
                        break;
                    case 'summer':
                        $months = [6, 7, 8];
                        break;
                }
                $data = Yii::$app->instagram->userMediaForMonths($user_id, $months);
            }

            if (isset($data['pagination']) && isset($data['pagination']['next_max_id'])) {
                $max_id = $data['pagination']['next_max_id'];
            } else {
                $max_id = null;
            }

            if (Yii::$app->request->isAjax) {
                return $this->renderPartial('_photos', ['photos' => $data['data'], 'max_id' => $max_id, 'user_id' => $user_id]);
            } else {
                return $this->render('choose', ['data' => $data, 'user_id' => $user_id, 'max_id' => $max_id]);
            }
        }
    }

    /**
     * Choose a wear
     *
     * @param null $id
     * @return string
     * @throws \yii\web\HttpException
     */
    public function actionWear($id = null)
    {
        if ($id == null) {
            $order = new Order();
            $order->user_id = Yii::$app->user->identity->id;

            if ($order->save()) {
                if (isset($_POST['photo'])) {
                    foreach ($_POST['photo'] as $instagram_id) {
                        $orderPhoto = new OrderPhoto();
                        $orderPhoto->instagram_id = $instagram_id;
                        $orderPhoto->order_id = $order->id;
                        if (!$orderPhoto->save()) {
                            throw new HttpException(500);
                        }
                    }
                    $this->redirect(['wear', 'id' => $order->id]);
                } else {
                    throw new HttpException(400);
                }
            } else {
                throw new HttpException(500);
            }
        } else {
            $order = Order::find()->where(['id' => $id])->one();
            if ($order != null) {
                if (Yii::$app->request->isPost) {
                    if ($order->load(Yii::$app->request->post())) {
                        $good = Good::find()->where(['type' => $_POST['Good']['type'], 'wear' => $_POST['Good']['wear']])->one();
                        if ($good != null) {
                            $order->good_id = $good->id;
                            if ($order->save()) {
                                $this->redirect(['site/form', 'id' => $order->id]);
                            }
                        } else {
                            throw new HttpException(500, 'Нельзя оформить заказ на несуществующий товар');
                        }
                    }
                }
            } else {
                throw new HttpException(404);
            }
        }
        return $this->render('wear', ['order' => $order]);
    }

    public function actionWearsizes($type, $wear)
    {
        $wear = Good::find()->where(['type' => $type, 'wear' => $wear])->one();
        return $this->renderPartial('wearsizes', ['good' => $wear]);
    }

    public function actionWearphotos($type, $wear)
    {
        $wear = Good::find()->where(['type' => $type, 'wear' => $wear])->one();
        return $this->renderPartial('wearphotos', ['good' => $wear]);
    }

    public function actionWearprices($type, $wear)
    {
        $wear = Good::find()->where(['type' => $type, 'wear' => $wear])->one();
        return $this->renderPartial('wearprices', ['good' => $wear]);
    }

    public function actionForm($id)
    {
        $order = Order::find()->where(['id' => $id])->one();

        if (($order->load(Yii::$app->request->post())) && ($order->save())) {
            $this->redirect(['site/thankyou']);
        }

        if ($order != null) {
            return $this->render('form', ['order' => $order]);
        } else {
            throw new HttpException(404);
        }
    }

    public function actionThankyou()
    {
        return $this->render('thankyou');
    }

    public function actionUpload($id = null, $delete_photo = null)
    {
        if ($delete_photo != null) {
            $photo = OrderPhoto::find()->where(['id' => $delete_photo])->one();
            if ($photo != null) {
                $photo->delete();
            }
            if (Yii::$app->request->isAjax) {
                return Json::encode(['status' => 'success']);
            } else {
                $this->redirect(['upload', 'id' => $id]);
            }
        }
        if ($id != null) {
            $order = Order::find()->where(['id' => $id])->one();
            if ($order == null) {
                throw new HttpException(404);
            }
        } else {
            $order = new Order();
        }

        if (Yii::$app->request->isPost) {
            $order->load(Yii::$app->request->post());
            if ($order->save()) {
                foreach ($_FILES['files']['error'] as $index => $value) {
                    if ($value == 0) {
                        $parts = explode('.', $_FILES['files']['name'][$index]);

                        $file_name = 'upload/n_' . time() . '_' . mt_rand(100000, 999999) . '.' . array_pop($parts);

                        if (move_uploaded_file($_FILES['files']['tmp_name'][$index], $file_name)) {
                            $orderPhoto = new OrderPhoto();
                            $orderPhoto->order_id = $order->id;
                            $orderPhoto->url = $file_name;
                            $orderPhoto->save();
                        }

                        if ($order->photoCount >= 20) {
                            break;
                        }
                    }
                }

                if (isset($_POST['OrderPhoto'])) {
                    foreach ($_POST['OrderPhoto'] as $id) {
                        $photo = OrderPhoto::find()->where(['id' => $id])->one();
                        $photo->order_id = $order->id;
                        $photo->save();
                    }
                }

                $this->redirect(['upload', 'id' => $order->id]);
            } else {
                throw new HttpException(500);
            }
        }
        return $this->render('upload', ['order' => $order]);
    }

    /**
     * @return string
     */
    public function actionUploadimage()
    {
        if ($_FILES['image']['error'] == 0) {
            $parts = explode('.', $_FILES['image']['name']);

            $file_name = 'upload/n_' . time() . '_' . mt_rand(100000, 999999) . '.' . array_pop($parts);

            if (move_uploaded_file($_FILES['image']['tmp_name'], $file_name)) {
                $orderPhoto = new OrderPhoto();
                $orderPhoto->url = $file_name;
                if ($orderPhoto->save()) {
                    $data['id'] = $orderPhoto->id;
                    $data['url'] = Yii::getAlias('@web') . '/' . $file_name;
                    return Json::encode($data);
                }
            }
        }
    }

    /**
     * Logout
     *
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

views/site/_gallery.php
<?php
use app\models\OrderPhoto;

/* @var $photos OrderPhoto[]  */
?>

views/site/_photos.php
<?php
use yii\base\View;
use yii\helpers\Url;

/* @var $this View */
/* @var $photos array */
/* @var $max_id string */
/* @var $user_id integer */

foreach ($photos as $media) {
    $photoDate = new DateTime(date("Y-m-d", $media['created_time']));
    $nowDate = new DateTime();

    $diff = $nowDate->diff($photoDate, true);

    $period = '';

    if (($diff->y == 0) && ($diff->m <= 11)) {
        $period = 'year';
    }

    if (($diff->y == 0) && ($diff->m <= 6)) {
        $period .= ' 6mon';
    }

    if ($diff->y >= 1) {
        $period = 'more_year';
    }

    $month = intval(date('m', intval($media['created_time'])));

    $season = '';
    switch ($month) {
        case 1:
        case 2:
        case 12:
            $season = 'winter';
            break;
        case 3:
        case 4:
        case 5:
            $season = 'spring';
            break;
        case 6:
        case 7:
        case 8:
            $season = 'summer';
            break;
        case 9:
        case 10:
        case 11:
            $season = 'fall';
            break;
    }
    ?>
<li class="item thumb <?= $season . ' ' . $period ?>" id="thumb-<?= $media['id'] ?>"
    data-next-url="<?= Url::to(['site/choose', 'user_id' => $user_id, 'max_id' => $max_id]) ?>">
    <figure>
        <div class="icon-overlay icn-link">
            <a href="#" onclick="return photoSelect(this);" data-photo-id="<?= $media['id'] ?>"
               data-likes="<?= $media['likes']['count'] ?>"
               data-selected="0" class="photo-item <?= $season . ' ' . $period ?>">
                <img src="<?= $media['images']['low_resolution']['url']; ?>" alt="" width="280" height="280">
            </a>
        </div>

        <figcaption class="bordered no-top-border">
            <div class="info">
                <h4>@<?= $media['user']['username'] ?></h4>

                <p><span
                        class="glyphicon glyphicon-heart"></span> <?= $media['likes']['count'] ?></p>
            </div>
        </figcaption>
    </figure>
    </li><?php
}
?>

views/site/error.php
<?php
/* @var $name */
/* @var $message */
/* @var $exception */
?>
<main>
    <section id="pattern-background-1" class="light-bg img-bg-softer"
             style="background-image: url(/images/art/pattern-background01.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1><?= $name; ?></h1>

                    <div class="alert alert-danger">
                        <?= $message ?>
                    </div>
                </div>
            </div>
        </div>
    </section>

</main>

views/site/form.php
<?php
/* @var $order \app\models\Order */
use yii\helpers\Html;

?>
<main>
    <section id="pattern-background-1" class="light-bg img-bg-softer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>Ваши данные</h1>
                    <?php $form = \yii\widgets\ActiveForm::begin(); ?>
                    <?= $form->field($order, 'name')->textInput(); ?>
                    <?= $form->field($order, 'phone')->textInput(); ?>
                    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']); ?>
                    <?php $form->end(); ?>
                </div>
            </div>
        </div>
    </section>
</main>

views/site/thankyou.php
<?php
/* */
?>
<main>
    <section id="pattern-background-1" class="light-bg img-bg-softer"
             style="background-image: url('<?= Yii::getAlias('@web') ?>/images/art/pattern-background01.jpg');">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>Спасибо за ваш заказ!</h1>
                </div>
            </div>
        </div>
    </section>
</main>

views/site/upload.php
<?php
use yii\helpers\Html;
use yii\base\View;
use app\models\Order;
use yii\helpers\Url;

/* @var $order Order */
/* @var $this View */

?>
<style>
    .files-drop {
        height: 200px;
        border: 3px dashed #000000;
        background-color: #afd9ee;
        border-radius: 5px;
        text-align: center;
        padding-top: 80px;
        font-size: 40px;
    }

    .files-drop.drag-hover {
        background-color: #269abc;
    }

    .thumbnail {
        margin-bottom: 0px;
        max-height: 120px;
    }

    .image-item {
        min-height: 150px;
    }

    .image-item .glyphicon {
        margin-bottom: 10px;
    }
</style>

<script>
    totalPhoto = 0;
    $(function () {
        $('.files-drop').on('dragover', function (e) {
            $(this).addClass('drag-hover');
            e.preventDefault();
            e.stopPropagation();
        });

        $('.files-drop').on('dragleave', function (e) {
            $(this).removeClass('drag-hover');
            e.preventDefault();
            e.stopPropagation();
        });

        $('.files-drop').on('dragover', function (e) {
            e.preventDefault();
            e.stopPropagation();
        });

        $('.files-drop').on('dragenter', function (e) {
            e.preventDefault();
            e.stopPropagation();
        });

        var uploadInProgress = false;

        function updateGallery() {

        }

        $('.files-drop').bind('drop', function (e) {
            if (uploadInProgress) return;
            if (e.originalEvent.dataTransfer) {
                if (e.originalEvent.dataTransfer.files.length) {
                    e.preventDefault();
                    e.stopPropagation();

                    if (totalPhoto >= 30) {
                        alert('Нельзя загрузить больше 30 фото!');
                        return;
                    }

                    uploadInProgress = true;

                    $('.files-drop').html('Загрузка...');

                    var filesToLoad = e.originalEvent.dataTransfer.files.length;
                    var filesLoaded = 0;
                    var filesQueue = [];

                    for (var i = e.originalEvent.dataTransfer.files.length - 1; i >= 0; i--) {
                        var file = e.originalEvent.dataTransfer.files[i];
                        filesQueue.push(file);
                    }

                    var fileNum = 0;

                    var loadNextFile = function () {
                        if (fileNum >= filesQueue.length) {
                            uploadInProgress = false;
                            $('.files-drop').html('Готово!');
                            $('.files-drop').removeClass('drag-hover');
                            return;
                        }
                        $('.files-drop').html('Загрузка ' + filesQueue[fileNum].name);
                        var xhr = new XMLHttpRequest();

                        xhr.onreadystatechange = function (e) {
                            if (e.target.readyState == 4) {
                                if (e.target.status == 200) {
                                    filesLoaded++;

                                    console.log(this.responseText);

                                    var obj = JSON.parse(this.responseText);
                                    var $el = $('<div/>', {
                                        'class': 'col-md-2 image-item',
                                        'id': 'photoContainer-' + obj.id
                                    });

                                    var $image = $('<img/>', {
                                        'src': obj.url,
                                        'class': 'thumbnail img-responsive'
                                    });

                                    var $hidden = $('<input/>', {
                                        'type': 'hidden',
                                        'name': 'OrderPhoto[]',
                                        'value': obj.id
                                    });

                                    var $link = $('<a/>', {
                                        'href': '<?= Url::to(['upload']) ?>?delete_photo=' + obj.id,
                                        'class': 'delete-photo',
                                        'data-photo-id': obj.id,
                                        'title': 'Удалить фотографию'
                                    });

                                    $link.append(
                                        $('<span/>', {
                                            'class': 'glyphicon glyphicon-remove'
                                        })
                                    );

                                    $el.append($image);
                                    $el.append($hidden);
                                    $el.append($link);

                                    $('#imagesContainer').append($el);

                                    totalPhoto++;

                                    $('#photoCount').html(totalPhoto);

                                    deleteEvent();

                                    fileNum++;
                                    loadNextFile();
                                }
                            }
                        };

                        xhr.open('POST', '<?= Url::to(['site/uploadimage']) ?>');

                        var fd = new FormData();
                        fd.append("image", filesQueue[fileNum]);
                        xhr.send(fd);
                    }

                    loadNextFile();
                }
            }
        });

        var deleteEvent = function () {
            $('.delete-photo').on('click', function (e) {
                e.preventDefault();

                var $this = $(this);
                $this.hide();
                var photoID = $(this).attr('data-photo-id');

                totalPhoto--;
                $('#photoCount').html(totalPhoto);
                if (totalPhoto < 9) {
                    $('#doneButton').addClass('disabled');
                }

                $.ajax({
                    url: '<?= Url::to(['upload']) ?>?delete_photo=' + photoID,
                    'dataType': 'json',
                    success: function (jData) {
                        $('#photoContainer-' + photoID).remove();
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        $this.show();
                        totalPhoto++;
                        $('#photoCount').html(totalPhoto);
                        if (totalPhoto >= 9) {
                            $('#doneButton').removeClass('disabled');
                        }
                    }
                });
            });
        };
        deleteEvent();

    });
</script>

<main>
    <section>
        <div class="container">
            <h1>Загрузка фото без Instagram</h1>

            <h2>Загруженно <span id="photoCount"><?= $order->photoCount; ?></span></h2>

            <form action="" method="post" enctype="multipart/form-data">

                <div class="row" id="imagesContainer">
                    <?php
                    if (!$order->isNewRecord) {
                        ?>
                        <script>
                            totalPhoto = <?= $order->photoCount; ?>;
                        </script>
                        <?php
                        foreach ($order->orderPhotos as $photo) {
                            ?>
                            <div class="col-md-2 image-item" id="photoContainer-<?= $photo->id ?>">
                                <input type="hidden" name="OrderPhoto[]" value="<?= $photo->id ?>">
                                <img src="<?= Yii::getAlias('@web') . '/' . $photo->url ?>" alt=""
                                     class="thumbnail img-responsive">
                                <?= Html::a('<span class="glyphicon glyphicon-remove"></span>', ['upload', 'id' => $order->id, 'delete_photo' => $photo->id], ['class' => 'delete-photo', 'data-photo-id' => $photo->id, 'title' => 'Удалить фотографию']); ?>
                            </div>
                        <?php
                        }
                    }
                    ?>
                </div>

                <?php
                if ($order->isNewRecord || $order->photoCount < 20) {
                    ?>
                    <div class="files-drop hidden-xs">
                        Перетащите фотографии сюда
                    </div>
                    <div class="form-group">
                        <label for="files">Выберите файлы</label>
                        <input type="file" accept="image/*" name="files[]" id="files" class="form-control" multiple>
                    </div>
                <?php
                }
                ?>
                <div class="form-group">
                    <label for="comment">Комментарий</label>
                    <?= Html::activeTextarea($order, 'comment', ['class' => 'form-control']); ?>
                </div>
                <div class="form-group">
                    <p>Необходимо загрузить не менее 9 и не более 30 фотографий. После загрузки нажмите "СОХРАНИТЬ" и
                        затем "ПРОДОЛЖИТЬ"</p>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                    <?php
                    echo Html::a('Продолжить', ['site/wear', 'id' => $order->id], ['class' => 'btn btn-primary' . (((!$order->isNewRecord) && ($order->photoCount >= 9)) ? '' : ' disabled'), 'id' => 'doneButton']);
                    ?>
                </div>
            </form>
        </div>
    </section>
</main>

views/site/wear.php
<?php
use app\models\Good;
use yii\bootstrap\Modal;

/* @var $this \yii\base\View */
/* @var $order \app\models\Order */

$this->title = 'Выбор одежды';

$sizeTable = Modal::begin([
    'header' => 'Таблица размеров',
    'options' => ['style' => "z-index: 9999"],
]);

$goods = Good::find()->all();
?>
<div id="sizesContainer"></div>
<?php

Modal::end();
?>
<style>
    #prices {
        margin-bottom: 30px;
        margin-top: 30px;
    }

    #prices .price-new {
        font-size: 40px;
        color: #fd6b62;
        text-align: right;
    }

    #prices .price-old {
        padding-top: 10px;
        text-align: left;
    }

    .updateRadio {
        width: 100%;
    }

    .updateRadio label.btn {
        background-color: #ffffff;
        color: #536a80 !important;
        box-shadow: none;
        border: 2px solid #536a80;
        text-transform: none;
        border-radius: 2px;
    }

    .btn-group > .btn:not(:first-child):not(:last-child):not(.dropdown-toggle) {
        border-right: none;
        border-left: none;
    }

    .btn-group > .btn:first-child {
        border-right: none;
    }

    .btn-group > .btn:last-child {
        border-left: none;
    }

    .updateRadio label..btn:not(:first-child):not(:last-child):not(.dropdown-toggle) {
        border-right: none;
        border-left: none;
    }

    .updateRadio label.btn.active, label.btn:hover {
        background-color: #536a80;
        color: #ffffff !important;
    }
</style>
<main>
    <section id="pattern-background-1" class="light-bg img-bg-softer">
        <div class="container" style="padding-top: 40px">
            <div class="row">
                <div class="col-md-8" id="photos">
                    <!-- placeholder -->
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="btn-group updateRadio" data-toggle="buttons">
                                <label class="btn btn-primary active" style="width: 33%">
                                    <input type="radio" name="type" id="typeMen" value="men" checked> Мужские
                                </label>
                                <label class="btn btn-primary" style="width: 34%">
                                    <input type="radio" name="type" id="typeWomen" value="women"> Женские
                                </label>
                                <label class="btn btn-primary" style="width: 33%">
                                    <input type="radio" name="type" id="typeKids" value="kids"> Детские
                                </label>
                            </div>

                            <div class="btn-group updateRadio" data-toggle="buttons">
                                <label class="btn btn-primary active" style="width: 50%">
                                    <input type="radio" name="wear" id="typeTShirts" value="t-shirt" checked> Футболки
                                </label>
                                <label class="btn btn-primary" style="width: 50%">
                                    <input type="radio" name="wear" id="typeSweatshirt" value="sweatshirt"> Свитшоты
                                </label>
                            </div>

                            <div class="btn-group updateRadio" data-toggle="buttons">
                                <label class="btn btn-primary active" style="width: 20%">
                                    <input type="radio" name="size" id="sizeXS" value="xs" checked> XS
                                </label>
                                <label class="btn btn-primary" style="width: 20%">
                                    <input type="radio" name="size" id="sizeX" value="s"> S
                                </label>
                                <label class="btn btn-primary" style="width: 20%">
                                    <input type="radio" name="size" id="sizeM" value="m"> M
                                </label>
                                <label class="btn btn-primary" style="width: 20%">
                                    <input type="radio" name="size" id="sizeL" value="l"> L
                                </label>
                                <label class="btn btn-primary" style="width: 20%">
                                    <input type="radio" name="size" id="sizeXL" value="xl"> XL
                                </label>
                            </div>

                            <p class="text-center">
                                <a href="#" data-toggle="modal" data-target="#<?= $sizeTable->id; ?>"
                                   style="border-bottom: none; font-size: 15px;"><span
                                        class="glyphicon glyphicon-tags" style="margin-right: 7px;"></span>Таблица
                                    размеров</a>
                            </p>
                        </div>
                    </div>
                    <div class="row" id="prices">
                        <!-- placeholder -->
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <button class="btn btn-primary btn-block btn-red" id="done">
                                Выбрать и перейти к шагу 4!
                            </button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <p class="text-center">
                                Специально для Вас напечатаем, сошьем и бесплатно отправим за 2 дня.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

</main>

<script>
    var timout = null;

    function updateData() {
        timout = null;

        var type = $('input[name=type]:checked').val();
        var wear = $('input[name=wear]:checked').val();

        $('#photos').load('<?= \yii\helpers\Url::to(['site/wearphotos']) ?>?type=' + type + '&wear=' + wear);
        $('#prices').load('<?= \yii\helpers\Url::to(['site/wearprices']) ?>?type=' + type + '&wear=' + wear);
        $('#sizesContainer').load('<?= \yii\helpers\Url::to(['site/wearsizes']) ?>?type=' + type + '&wear=' + wear);
    }

    $(function () {
        $('.updateRadio').on('mouseup', function () {
            if (timout != null) {
                clearTimeout(timout);
            }
            timout = setTimeout(updateData, 100);
        });

        $('#done').on('click', function (e) {
            var type = $('input[name=type]:checked').val();
            var wear = $('input[name=wear]:checked').val();
            var size = $('input[name=size]:checked').val();

            var form = document.createElement('form');

            form.setAttribute('method', 'post');
            form.setAttribute('action', '<?= \yii\helpers\Url::to(['site/wear', 'id' => $order->id]) ?>');

            var typeInput = document.createElement('input');
            typeInput.setAttribute('type', 'hidden');
            typeInput.setAttribute('value', type);
            typeInput.setAttribute('name', 'Good[type]');
            form.appendChild(typeInput);

            var wearInput = document.createElement('input');
            wearInput.setAttribute('type', 'hidden');
            wearInput.setAttribute('value', wear);
            wearInput.setAttribute('name', 'Good[wear]');
            form.appendChild(wearInput);

            var sizeInput = document.createElement('input');
            sizeInput.setAttribute('type', 'hidden');
            sizeInput.setAttribute('value', size);
            sizeInput.setAttribute('name', 'Order[size]');
            form.appendChild(sizeInput);

            document.body.appendChild(form);

            form.submit();
        });

        updateData();
    });
</script>

views/site/wearsizes.php
<?php
/**
 * Created by PhpStorm.
 * User: michaelmiriti
 * Date: 07/10/14
 * Time: 22:43
 */
echo $good->sizes;